using System;
using System.Collections.Generic;

namespace Reci
{
    public class Reci
    {
        public List<string> reci = new List<string>()
        {
            "Kim Dzong Un",
            "Krema za suncanje",
            "Novi Sad",
            "Jevreji",
            "Suncobran",
            "Maunt Everest",
            "Dzoni Dep",
            "Nikola Tesla",
            "Banana",
            "Struja",
            "Ajfon",
            "Mesec",
            "Patike",
            "Crna Gora",
            "Italija",
            "Kina",
            "Labubu",
            "Bombardiro Krokodilo",
            "Tralalero Tralala",
            "Majnkraft",
            "Pivo",
            "Votka",
            "Krompir",
            "Sarma",
            "Saturn",
            "Voz",
            "Majkl Dzekson",
            "Vucic",
            "Teretana",
            "Titanik",
            "Rolex",
            "Adidas",
            "Pepa prase",
            "Winx",
            "Kod Lioko",
            "Sundjer Bob",
            "Doktor",
            "Učitelj",
            "Policajac",
            "Glumac",
            "Pilot",
            "Pekar",
            "Kuhar",
            "Programer",
            "Zidar",
            "Vojnik",
            "Avion",
            "Brod",
            "Voz",
            "Bicikl",
            "Auto",
            "Traktor",
            "Helikopter",
            "Skuter",
            "Autobus",
            "Motor",
            "Bolnica",
            "Škola",
            "Crkva",
            "Igralište",
            "Plaža",
            "Park",
            "Zatvor",
            "Stadion",
            "Bioskop",
            "Biblioteka",
            "Kafa",
            "Voda",
            "Mleko",
            "Čaj",
            "Sok",
            "Pizza",
            "Hleb",
            "Supa",
            "Torta",
            "Sladoled",
            "Ajkula",
            "Ajkula čekićara",
            "Ana Frank",
            "Atina",
            "Audi",
            "Australija",
            "Balet",
            "Barak Obama",
            "Barcelona",
            "Basna",
            "Bazen",
            "Biber",
            "Biciklistička staza",
            "Bik",
            "Blic",
            "Bob Marley",
            "Boja",
            "Boing 747",
            "Božić",
            "Bube",
            "Burj Khalifa",
            "Ceo svet",
            "Crtaći",
            "Ćevapi",
            "Ćilim",
            "Čajnik",
            "Časovnik",
            "Četkica za zube",
            "Čokolada",
            "Čovek-pauk",
            "Čuvari galaksije",
            "Deda Mraz",
            "Delfin",
            "Despacito",
            "Detektiv",
            "Dinamit",
            "Dinosaurus",
            "Disko kugla",
            "Divlja svinja",
            "Donald Tramp",
            "Drvo",
            "Džepni nož",
            "Džungla",
            "Egipat",
            "Ekser",
            "Ekspres lonac",
            "Električni trotinet",
            "Engleska",
            "Everest",
            "Fabrika",
            "Fantomka",
            "Farmerke",
            "Fen za kosu",
            "FIFA",
            "Foka",
            "Frizbi",
            "Galaksija",
            "Galeb",
            "Garfield",
            "Gimnazija",
            "Gitara",
            "Gluva soba",
            "Gorila",
            "Grad",
            "Grčka",
            "Guske",
            "Hamburger",
            "Harmonika",
            "Havaji",
            "Hemijska olovka",
            "Holandija",
            "Hrana",
            "Hulk",
            "Ikea",
            "Iran",
            "Izvor",
            "Japan",
            "Jednorog",
            "Jezero",
            "Joga",
            "Jugoslavija",
            "Kaktus",
            "Kamera",
            "Kanada",
            "Kapetan",
            "Kapija",
            "Karate",
            "Karta",
            "Kaseta",
            "Keks",
            "Koala",
            "Kobasica",
            "Kofer",
            "Kompjuter",
            "Kornjača",
            "Kosa",
            "Krevet",
        };

        public string VratiRandomRec()
        {
            Random random = new Random();
            
            int randomIndex = random.Next(0, reci.Count); 
            string randomElement = reci[randomIndex];
            reci.Remove(randomElement);

            return randomElement;
        }
    }
}
